import { Types } from "mongoose";

const MOCKED_PLAYER = {
  _id: new Types.ObjectId("66e96076be0f1b9dc7e4632a"),
  pushToken:
    "cr-vJwtQT2e5SySQhhD7bo:APA91bH1K9zFQKs5cP2AlQBFM0aE4C8MEJ8aSFQEs77F5U3AyD0S1HE-FYnitgLG-WO1pvCY6PCMkgI4BLCsWNoK_AeNhjTqrTlIiOWXp678O_oSv62mAZk",
  active: true,
  rol: "acolyte",
  socketId: "l2TGiwvy7eDChGyCAAAB",
  attributes: {
    intelligence: 34,
    dexterity: 49,
    charisma: 57,
    constitution: 68,
    strength: 78,
    insanity: 24,
    resistance: 100,
  },
  equipment: {
    helmet: {
      modifiers: {
        intelligence: 0,
        dexterity: 2,
        charisma: 2,
        constitution: 2,
        strength: 0,
        insanity: -2,
      },
      name: "Helm of Infinite Vengeance",
      description: "Infused with the rage of fallen gods.",
      type: "helmet",
      image: "/images/equipment/helmets/full_helmet_5.png",
      value: 2400,
      min_lvl: 20,
      defense: 48,
      isUnique: true,
      isActive: false,
      _id: new Types.ObjectId("66fa4bea85f0d4f8e349daa2"),
    },
    weapon: {
      modifiers: {
        intelligence: 0,
        dexterity: -1,
        charisma: 1,
        constitution: 1,
        strength: 3,
        insanity: 0,
      },
      name: "Sword of the Eternal Eclipse",
      description: "A sword that exists in both light and darkness.",
      type: "weapon",
      image: "/images/equipment/weapons/sword_78.png",
      value: 9200,
      min_lvl: 14,
      base_percentage: 18,
      die_faces: 12,
      die_modifier: 3,
      die_num: 8,
      isUnique: false,
      isActive: true,
      _id: new Types.ObjectId("66fa619885f0d4f8e349daf6"),
    },
    armor: {
      modifiers: {
        intelligence: 2,
        dexterity: 1,
        charisma: 0,
        constitution: 0,
        strength: 0,
        insanity: 1,
      },
      name: "Anger Plate",
      description: "Forged in the heart of a dying titan.",
      type: "armor",
      image: "/images/equipment/armors/armor_66.webp",
      value: 8200,
      min_lvl: 15,
      defense: 197,
      isUnique: false,
      isActive: true,
      _id: new Types.ObjectId("6912eecff6c013b737606008"),
    },
    shield: {
      modifiers: {
        intelligence: 1,
        dexterity: 0,
        charisma: 4,
        constitution: 3,
        strength: 0,
        insanity: 0,
      },
      name: "Shield of the Ironclad",
      description: "An impenetrable shield forged in iron.",
      type: "shield",
      image: "/images/equipment/shields/shield_52.png",
      value: 280,
      min_lvl: 18,
      defense: 48,
      isUnique: true,
      isActive: false,
      _id: new Types.ObjectId("66f27ec7c114335cadf45da4"),
    },
    artifact: {
      modifiers: {
        intelligence: 7,
        dexterity: 1,
        charisma: 0,
        constitution: 0,
        strength: 0,
        insanity: 0,
      },
      name: "Relic of the Haunted Depths",
      description: "Whispers from abyssal pits awaken nightmares.",
      type: "artifact",
      image: "/images/equipment/artifacts/artifact_67.png",
      value: 4878,
      min_lvl: 26,
      isActive: false,
      isUnique: true,
      _id: new Types.ObjectId("690f74bebce77974f15d7488"),
    },
    boot: {
      modifiers: {
        intelligence: 3,
        dexterity: 1,
        charisma: 0,
        constitution: 2,
        strength: 1,
        insanity: -2,
      },
      name: "Warlord's Fury Boots",
      description: "Radiate power and command respect.",
      type: "boot",
      image: "/images/equipment/boots/full_boot_10.png",
      value: 2100,
      min_lvl: 24,
      defense: 50,
      isActive: false,
      isUnique: true,
      _id: new Types.ObjectId("66f695614a8f1157dab87be6"),
    },
    ring: {
      modifiers: {
        intelligence: 0,
        dexterity: 3,
        charisma: 0,
        constitution: 0,
        strength: 0,
        insanity: 0,
      },
      name: "Band of the Lurking Shadow",
      description: "Moves unseen as darkness falls.",
      type: "ring",
      image: "/images/equipment/rings/ring_129.webp",
      value: 1200,
      min_lvl: 17,
      isUnique: false,
      isActive: true,
      _id: new Types.ObjectId("6910f401152a6b9e175c126a"),
    },
    antidote_potion: {
      name: "Antidote of Wailing Plague",
      description:
        "A cooling elixir brewed from the leaves of the Frostmind plant, alleviating migraines and clearing hallucinations.",
      type: "antidote",
      image: "/images/equipment/potions/antidote/antidote_3.png",
      value: 10,
      min_lvl: 1,
      recovery_effect: {
        modifiers: {
          hit_points: 0,
          intelligence: 0,
          dexterity: 0,
          charisma: -9,
          constitution: 0,
          strength: 0,
          insanity: 7,
        },
        name: "Wailing Plague",
        description:
          "An infectious disease that causes the afflicted to uncontrollably wail in pain, spreading misery and despair.",
        type: "illness",
        antidote_effects: [
          "lesser_restore_insanity",
          "lesser_restore_charisma",
        ],
        poison_effects: ["lesser_damage_insanity", "lesser_damage_charisma"],
        _id: new Types.ObjectId("6693fd5846527d0df5f0efe9"),
      },
      _id: new Types.ObjectId("668bca125319ea9afdff0764"),
    },
    healing_potion: {
      modifiers: {
        hit_points: 70,
        intelligence: -15,
        dexterity: 0,
        charisma: 0,
        constitution: 0,
        strength: 0,
        insanity: 0,
      },
      name: "Essence of Restoration",
      description:
        "The Essence of Restoration is a potent elixir that accelerates healing and revitalizes the body.",
      type: "essence",
      image: "/images/equipment/potions/healing/healing_3.png",
      value: 10,
      min_lvl: 1,
      _id: new Types.ObjectId("668bca125319ea9afdff0759"),
    },
    enhancer_potion: {
      modifiers: {
        intelligence: 0,
        dexterity: 0,
        charisma: 0,
        constitution: 0,
        strength: 0,
        insanity: 20,
      },
      name: "Elixir of Madness",
      description:
        "A dangerous brew that plunges the drinker into a frenzy, this potion unleashes chaotic energy.",
      type: "elixir",
      image: "/images/equipment/potions/enhancer/enhancer_2.png",
      value: 10,
      min_lvl: 1,
      duration: 2,
      _id: new Types.ObjectId("668bca135319ea9afdff076b"),
    },
  },
  inventory: {
    helmets: [
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 1,
        },
        name: "Eternal Guardian Helmet",
        description: "A helmet blessed by the spirits.",
        type: "helmet",
        image: "/images/equipment/helmets/helmet_initial.png",
        value: 5,
        min_lvl: 1,
        defense: 3,
        _id: new Types.ObjectId("66d99aac7518eb4990035363"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 1,
          charisma: 1,
          constitution: 0,
          strength: 1,
          insanity: -1,
        },
        name: "Sunfire Helm",
        description: "Radiates the light of a thousand suns.",
        type: "helmet",
        image: "/images/equipment/helmets/helmet_23.png",
        value: 220,
        min_lvl: 12,
        defense: 30,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3b3ddc8cdd090db911d94"),
      },
      {
        modifiers: {
          intelligence: 1,
          dexterity: 0,
          charisma: 1,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Titan's Crown",
        description: "Forged for the rulers of giants.",
        type: "helmet",
        image: "/images/equipment/helmets/helmet_17.png",
        value: 180,
        min_lvl: 10,
        defense: 26,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3b3ddc8cdd090db911d8e"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 1,
          insanity: 2,
        },
        name: "Helm of the Phoenix",
        description: "Rebirth from the ashes of defeat.",
        type: "helmet",
        image: "/images/equipment/helmets/helmet_3.png",
        value: 200,
        min_lvl: 11,
        defense: 28,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3b3ddc8cdd090db911d80"),
      },
      {
        modifiers: {
          intelligence: 2,
          dexterity: 1,
          charisma: 0,
          constitution: 1,
          strength: 3,
          insanity: -2,
        },
        name: "Helmet of the Enduring Seeker",
        description: "Calmness reigns in endless motion.",
        type: "helmet",
        image: "/images/equipment/helmets/full_helmet_60.webp",
        value: 5139,
        min_lvl: 26,
        defense: 82,
        isUnique: true,
        isActive: false,
        _id: new Types.ObjectId("6911c78001ef7575afbf7bd9"),
      },
    ],
    weapons: [
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 1,
          constitution: -2,
          strength: 3,
          insanity: 0,
        },
        name: "Whisper Fang",
        description: "A light, sharp sword that cracks under pressure.",
        type: "weapon",
        image: "/images/equipment/weapons/sword_init_1.png",
        value: 10,
        min_lvl: 1,
        base_percentage: 5,
        die_faces: 10,
        die_modifier: 3,
        die_num: 2,
        _id: new Types.ObjectId("668bca105319ea9afdff0716"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 2,
          charisma: 1,
          constitution: 0,
          strength: 3,
          insanity: 0,
        },
        name: "Soul Shatter",
        description: "A sword that fractures the spirits of those it strikes.",
        type: "weapon",
        image: "/images/equipment/weapons/sword_46.png",
        value: 800,
        min_lvl: 13,
        base_percentage: 12,
        die_faces: 10,
        die_modifier: 0,
        die_num: 7,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f9caddd39859521ad20fe8"),
      },
      {
        modifiers: {
          intelligence: 2,
          dexterity: 2,
          charisma: 0,
          constitution: 0,
          strength: 3,
          insanity: 0,
        },
        name: "Flame Reaver",
        description: "A sword engulfed in flames, scorching its foes.",
        type: "weapon",
        image: "/images/equipment/weapons/sword_22.png",
        value: 450,
        min_lvl: 9,
        base_percentage: 12,
        die_faces: 10,
        die_modifier: 5,
        die_num: 7,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f9ca51d39859521ad20fdb"),
      },
      {
        modifiers: {
          intelligence: -1,
          dexterity: -1,
          charisma: 2,
          constitution: 1,
          strength: 3,
          insanity: -1,
        },
        name: "Shadow's Whisper",
        description: "A sleek sword that moves silently through the air.",
        type: "weapon",
        image: "/images/equipment/weapons/sword_24.png",
        value: 600,
        min_lvl: 11,
        base_percentage: 12,
        die_faces: 10,
        die_modifier: 2,
        die_num: 8,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f9ca51d39859521ad20fdd"),
      },
      {
        modifiers: {
          intelligence: -1,
          dexterity: 1,
          charisma: 1,
          constitution: 1,
          strength: 4,
          insanity: 2,
        },
        name: "Stormbreaker",
        description: "A sword that brings down storms with its power.",
        type: "weapon",
        image: "/images/equipment/weapons/sword_49.png",
        value: 800,
        min_lvl: 13,
        base_percentage: 12,
        die_faces: 12,
        die_modifier: 3,
        die_num: 7,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f9caddd39859521ad20feb"),
      },
      {
        modifiers: {
          intelligence: 3,
          dexterity: 1,
          charisma: -2,
          constitution: 1,
          strength: 4,
          insanity: 0,
        },
        name: "Guardian's Edge",
        description: "A sturdy sword that stands the test of time.",
        type: "weapon",
        image: "/images/equipment/weapons/sword_10.png",
        value: 100,
        min_lvl: 3,
        base_percentage: 5,
        die_faces: 10,
        die_modifier: 7,
        die_num: 4,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f98473f9a28c1fef4dfcba"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 1,
          charisma: 0,
          constitution: 1,
          strength: 3,
          insanity: 0,
        },
        name: "Thunderstrike Hammer",
        description: "A medium hammer that crackles with thunderous force.",
        type: "weapon",
        image: "/images/equipment/weapons/hammer_4.png",
        value: 200,
        min_lvl: 5,
        base_percentage: 8,
        die_faces: 10,
        die_modifier: 8,
        die_num: 3,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f98116f9a28c1fef4dfcae"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 2,
          constitution: 1,
          strength: 12,
          insanity: 0,
        },
        name: "Blade of Eternal Night",
        description: "A sword that thrives in darkness.",
        type: "weapon",
        image: "/images/equipment/weapons/sword_66.png",
        value: 17200,
        min_lvl: 22,
        base_percentage: 18,
        die_faces: 12,
        die_modifier: 2,
        die_num: 6,
        isUnique: true,
        isActive: false,
        _id: new Types.ObjectId("66fa619885f0d4f8e349daea"),
      },
      {
        modifiers: {
          intelligence: -1,
          dexterity: 0,
          charisma: 0,
          constitution: 1,
          strength: 3,
          insanity: 0,
        },
        name: "Silver Saber",
        description: "A shimmering sword made of fine silver.",
        type: "weapon",
        image: "/images/equipment/weapons/sword_19.png",
        value: 200,
        min_lvl: 5,
        base_percentage: 8,
        die_faces: 6,
        die_modifier: 4,
        die_num: 3,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f985c5f9a28c1fef4dfcc4"),
      },
    ],
    armors: [
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 1,
          constitution: 0,
          strength: 1,
          insanity: 1,
        },
        name: "Knight's Vest",
        description: "The standard armor for knights in training.",
        type: "armor",
        image: "/images/equipment/armors/armor_13.png",
        value: 150,
        min_lvl: 4,
        defense: 46,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3cf18b32d7add9a087626"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 1,
          insanity: 1,
        },
        name: "Fashionable Rain Jacket",
        description: "A fashionable rain jacket to keep you dry and stylish.",
        type: "armor",
        image: "/images/equipment/armors/jacket_16.png",
        value: 60,
        min_lvl: 3,
        defense: 24,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3e3e1b32d7add9a0876a7"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 1,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Bulwark Jacket",
        description: "sacrifices agility for defense.",
        type: "armor",
        image: "/images/equipment/armors/jacket_4.png",
        value: 10,
        min_lvl: 1,
        defense: 30,
        _id: new Types.ObjectId("668bca105319ea9afdff0700"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 1,
        },
        name: "Guard Captain's Plate",
        description: "Worn by elite guard captains.",
        type: "armor",
        image: "/images/equipment/armors/armor_15.png",
        value: 170,
        min_lvl: 4,
        defense: 50,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3cf18b32d7add9a087628"),
      },
      {
        modifiers: {
          intelligence: 1,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Lightweight Summer Jacket",
        description: "A lightweight summer jacket for warm evenings.",
        type: "armor",
        image: "/images/equipment/armors/jacket_14.png",
        value: 30,
        min_lvl: 1,
        defense: 20,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3e3e1b32d7add9a0876a5"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 1,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Formal Blazer Jacket",
        description: "A formal blazer jacket suitable for business events.",
        type: "armor",
        image: "/images/equipment/armors/jacket_13.png",
        value: 90,
        min_lvl: 4,
        defense: 29,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3e3e1b32d7add9a0876a4"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 1,
          charisma: 1,
          constitution: 1,
          strength: 0,
          insanity: 0,
        },
        name: "Fiery Armor",
        description: "An armor that grants fire resistance and a fiery aura.",
        type: "armor",
        image: "/images/equipment/armors/heavy_armor_16.png",
        value: 720,
        min_lvl: 13,
        defense: 85,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3dfb5b32d7add9a087684"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 1,
          charisma: 1,
          constitution: 0,
          strength: 0,
          insanity: 1,
        },
        name: "Champion's Plate",
        description: "Worn by the arena champions.",
        type: "armor",
        image: "/images/equipment/armors/armor_27.png",
        value: 400,
        min_lvl: 8,
        defense: 66,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3d18db32d7add9a087635"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 2,
          charisma: 1,
          constitution: 0,
          strength: 0,
          insanity: 1,
        },
        name: "Guardian's Armament",
        description:
          "A special armor that protects its bearer with ancient magic.",
        type: "armor",
        image: "/images/equipment/armors/heavy_armor_28.png",
        value: 870,
        min_lvl: 15,
        defense: 75,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3e0f7b32d7add9a087691"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 1,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Formal Blazer Jacket",
        description: "A formal blazer jacket suitable for business events.",
        type: "armor",
        image: "/images/equipment/armors/jacket_13.png",
        value: 90,
        min_lvl: 4,
        defense: 29,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3e3e1b32d7add9a0876a4"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 2,
          constitution: 0,
          strength: 0,
          insanity: 1,
        },
        name: "Light Leather Armor",
        description: "A lightweight leather armor providing basic protection.",
        type: "armor",
        image: "/images/equipment/armors/leather_armor_1.png",
        value: 210,
        min_lvl: 5,
        defense: 45,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3e7ecb32d7add9a0876a9"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 1,
          insanity: 1,
        },
        name: "Cozy Fleece Jacket",
        description: "A cozy fleece jacket perfect for layering.",
        type: "armor",
        image: "/images/equipment/armors/jacket_15.png",
        value: 40,
        min_lvl: 2,
        defense: 22,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3e3e1b32d7add9a0876a6"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 1,
        },
        name: "Guard Captain's Plate",
        description: "Worn by elite guard captains.",
        type: "armor",
        image: "/images/equipment/armors/armor_15.png",
        value: 170,
        min_lvl: 4,
        defense: 50,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3cf18b32d7add9a087628"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 1,
          charisma: 2,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Puffer Jacket",
        description: "A warm puffer jacket for those cold days.",
        type: "armor",
        image: "/images/equipment/armors/jacket_11.png",
        value: 50,
        min_lvl: 2,
        defense: 23,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3e3e1b32d7add9a0876a2"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 1,
          strength: 0,
          insanity: 0,
        },
        name: "Sorceress's Ensemble",
        description: "An elegant robe for powerful sorceresses.",
        type: "armor",
        image: "/images/equipment/armors/robe_13.png",
        value: 360,
        min_lvl: 8,
        defense: 50,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3dc80b32d7add9a08765e"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 1,
        },
        name: "Robe of the Celestial",
        description: "A robe that reflects the power of the cosmos.",
        type: "armor",
        image: "/images/equipment/armors/robe_16.png",
        value: 480,
        min_lvl: 8,
        defense: 58,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3dc80b32d7add9a087661"),
      },
      {
        modifiers: {
          intelligence: 2,
          dexterity: 0,
          charisma: 1,
          constitution: 2,
          strength: -1,
          insanity: -2,
        },
        name: "Legendary Guardian Armor",
        description:
          "An armor that embodies the spirit of legendary guardians.",
        type: "armor",
        image: "/images/equipment/armors/heavy_armor_38.png",
        value: 20000,
        min_lvl: 26,
        defense: 250,
        isUnique: true,
        isActive: false,
        _id: new Types.ObjectId("66f3e2d6b32d7add9a08769c"),
      },
    ],
    shields: [
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 1,
          constitution: 0,
          strength: 0,
          insanity: 2,
        },
        name: "Knight's Shield",
        description: "A sturdy shield for knights.",
        type: "shield",
        image: "/images/equipment/shields/shield_initial.png",
        value: 15,
        min_lvl: 1,
        defense: 10,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f27c81c114335cadf45d70"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 2,
        },
        name: "Warrior's Shield",
        description: "A shield for brave warriors.",
        type: "shield",
        image: "/images/equipment/shields/shield_8.png",
        value: 23,
        min_lvl: 4,
        defense: 12,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f27c81c114335cadf45d77"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: -1,
          constitution: 0,
          strength: 0,
          insanity: -2,
        },
        name: "Runic Aegis",
        description:
          "A shield with ancient runes that provide magical defense.",
        type: "shield",
        image: "/images/equipment/shields/shield_40.png",
        value: 200,
        min_lvl: 12,
        defense: 30,
        isUnique: true,
        isActive: false,
        _id: new Types.ObjectId("66f27c81c114335cadf45d97"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 2,
        },
        name: "Guardian Shield",
        description: "A shield used by guardians to protect the realm.",
        type: "shield",
        image: "/images/equipment/shields/shield_10.png",
        value: 21,
        min_lvl: 4,
        defense: 11,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f27c81c114335cadf45d79"),
      },
      {
        modifiers: {
          intelligence: 1,
          dexterity: 0,
          charisma: 0,
          constitution: 1,
          strength: 0,
          insanity: 1,
        },
        name: "Spirit Guardian Shield",
        description: "A shield that connects the bearer to the spirits.",
        type: "shield",
        image: "/images/equipment/shields/shield_30.png",
        value: 50,
        min_lvl: 5,
        defense: 28,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f27c81c114335cadf45d8d"),
      },
    ],
    artifacts: [
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 1,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Crown of Eternal Wisdom",
        description: "This golden crown enhances intellect and wisdom.",
        type: "artifact",
        image: "/images/equipment/artifacts/artifact_2.png",
        value: 787,
        min_lvl: 1,
        _id: new Types.ObjectId("66a902e1b5831810990551d2"),
      },
      {
        modifiers: {
          intelligence: 3,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Amulet of Silent Shadows",
        description: "Perfect for moving unseen.",
        type: "artifact",
        image: "/images/equipment/artifacts/artifact_8.png",
        value: 1259,
        min_lvl: 7,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f66acd4a8f1157dab87b5c"),
      },
      {
        modifiers: {
          intelligence: 3,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Amulet of Silent Shadows",
        description: "Perfect for moving unseen.",
        type: "artifact",
        image: "/images/equipment/artifacts/artifact_8.png",
        value: 1259,
        min_lvl: 7,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f66acd4a8f1157dab87b5c"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 2,
          strength: 0,
          insanity: 0,
        },
        name: "Amulet of Phantom Veil",
        description: "Shrouds the wearer in illusions.",
        type: "artifact",
        image: "/images/equipment/artifacts/artifact_14.png",
        value: 1183,
        min_lvl: 10,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f66ae44a8f1157dab87b63"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 3,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: -2,
        },
        name: "Amulet of Eternal Flame",
        description: "Burns with an unquenchable fire.",
        type: "artifact",
        image: "/images/equipment/artifacts/artifact_12.png",
        value: 1303,
        min_lvl: 15,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f66acd4a8f1157dab87b60"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: -1,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 2,
        },
        name: "Amulet of Stone's Resilience",
        description: "Endows the wearer with great resilience.",
        type: "artifact",
        image: "/images/equipment/artifacts/artifact_7.png",
        value: 1683,
        min_lvl: 9,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f66acd4a8f1157dab87b5b"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 3,
          insanity: 0,
        },
        name: "Amulet of Whispering Breath",
        description: "Murmurs secrets beyond the veil.",
        type: "artifact",
        image: "/images/equipment/artifacts/artifact_103.png",
        value: 948,
        min_lvl: 15,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("691193ce01ef7575afbf7b5b"),
      },
    ],
    boots: [
      {
        modifiers: {
          intelligence: 0,
          dexterity: 1,
          charisma: 0,
          constitution: 1,
          strength: 0,
          insanity: 0,
        },
        name: "Beggar's path",
        description: "Cheap sinister leather shoes.",
        type: "boot",
        image: "/images/equipment/boots/boot_initial.png",
        value: 5,
        min_lvl: 1,
        defense: 4,
        _id: new Types.ObjectId("66d99a807518eb499003535f"),
      },
      {
        modifiers: {
          intelligence: 2,
          dexterity: 2,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Venomous Boots",
        description: "Step lightly, leave poison in your wake.",
        type: "boot",
        image: "/images/equipment/boots/boot_23.png",
        value: 440,
        min_lvl: 16,
        defense: 39,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f694d84a8f1157dab87bcf"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 2,
          charisma: 0,
          constitution: 1,
          strength: 0,
          insanity: 0,
        },
        name: "Celestial Boots",
        description: "Woven from the fabric of the stars.",
        type: "boot",
        image: "/images/equipment/boots/boot_24.png",
        value: 460,
        min_lvl: 17,
        defense: 41,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f694d84a8f1157dab87bd0"),
      },
      {
        modifiers: {
          intelligence: 3,
          dexterity: 2,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Chaoswalker Boots",
        description: "Step through the realms of chaos.",
        type: "boot",
        image: "/images/equipment/boots/boot_25.png",
        value: 480,
        min_lvl: 18,
        defense: 43,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f694d84a8f1157dab87bd1"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 2,
          charisma: 0,
          constitution: 1,
          strength: 0,
          insanity: 0,
        },
        name: "Celestial Boots",
        description: "Woven from the fabric of the stars.",
        type: "boot",
        image: "/images/equipment/boots/boot_24.png",
        value: 460,
        min_lvl: 17,
        defense: 41,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f694d84a8f1157dab87bd0"),
      },
      {
        modifiers: {
          intelligence: 3,
          dexterity: 1,
          charisma: 0,
          constitution: 1,
          strength: 0,
          insanity: 0,
        },
        name: "Guardian's Light Boots",
        description: "Shines with divine energy.",
        type: "boot",
        image: "/images/equipment/boots/boot_29.png",
        value: 560,
        min_lvl: 22,
        defense: 51,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f694d84a8f1157dab87bd5"),
      },
      {
        modifiers: {
          intelligence: 1,
          dexterity: 2,
          charisma: 0,
          constitution: 2,
          strength: 0,
          insanity: 0,
        },
        name: "Phoenix Feather Boots",
        description: "Reborn from ashes, they give life.",
        type: "boot",
        image: "/images/equipment/boots/boot_30.png",
        value: 580,
        min_lvl: 23,
        defense: 53,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f694d84a8f1157dab87bd6"),
      },
      {
        modifiers: {
          intelligence: 3,
          dexterity: 1,
          charisma: 0,
          constitution: 1,
          strength: 0,
          insanity: 0,
        },
        name: "Infinity Boots",
        description: "A gateway to limitless possibilities.",
        type: "boot",
        image: "/images/equipment/boots/boot_34.png",
        value: 660,
        min_lvl: 27,
        defense: 61,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f694ea4a8f1157dab87bdb"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: -1,
          charisma: 2,
          constitution: 2,
          strength: 1,
          insanity: 1,
        },
        name: "Boots of the Kaotika Sage",
        description: "Worn by the wisest in the land of chaos.",
        type: "boot",
        image: "/images/equipment/boots/full_boot_2.png",
        value: 1300,
        min_lvl: 16,
        defense: 34,
        isActive: false,
        isUnique: true,
        _id: new Types.ObjectId("66f695614a8f1157dab87bde"),
      },
      {
        modifiers: {
          intelligence: 1,
          dexterity: 2,
          charisma: 0,
          constitution: 2,
          strength: 0,
          insanity: 0,
        },
        name: "Phoenix Feather Boots",
        description: "Reborn from ashes, they give life.",
        type: "boot",
        image: "/images/equipment/boots/boot_30.png",
        value: 580,
        min_lvl: 23,
        defense: 53,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f694d84a8f1157dab87bd6"),
      },
      {
        modifiers: {
          intelligence: 1,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Hunter's Trail Boots",
        description: "Ideal for tracking and hunting.",
        type: "boot",
        image: "/images/equipment/boots/boot_6.png",
        value: 300,
        min_lvl: 10,
        defense: 26,
        isActive: true,
        isUnique: false,
        _id: new Types.ObjectId("66f694d84a8f1157dab87bbe"),
      },
    ],
    rings: [
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 3,
        },
        name: "Ring of Eternal Flame",
        description: "A ring that burns with eternal fire.",
        type: "ring",
        image: "/images/equipment/rings/ring_1.png",
        value: 10,
        min_lvl: 1,
        _id: new Types.ObjectId("66a6d6c8dfbffe7e6503970f"),
      },
      {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 0,
          strength: 3,
          insanity: 0,
        },
        name: "Ring of the Eternal Flame",
        description: "A ring that blazes with unending fire.",
        type: "ring",
        image: "/images/equipment/rings/ring_2.png",
        value: 150,
        min_lvl: 6,
        isUnique: false,
        isActive: true,
        _id: new Types.ObjectId("66f3c85ec8cdd090db911da5"),
      },
      {
        modifiers: {
          intelligence: -2,
          dexterity: 1,
          charisma: 0,
          constitution: 0,
          strength: 0,
          insanity: 6,
        },
        name: "Ring of the Arcane Guardian",
        description: "A protector's ring, imbued with arcane might.",
        type: "ring",
        image: "/images/equipment/rings/ring_17.png",
        value: 350,
        min_lvl: 11,
        isUnique: true,
        isActive: false,
        _id: new Types.ObjectId("66f3c85ec8cdd090db911db0"),
      },
      {
        modifiers: {
          intelligence: 4,
          dexterity: -1,
          charisma: 3,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        name: "Ring of the Crystal Sage",
        description: "Clarity shining through cracked crystal.",
        type: "ring",
        image: "/images/equipment/rings/ring_120.webp",
        value: 4350,
        min_lvl: 24,
        isUnique: true,
        isActive: false,
        _id: new Types.ObjectId("6910f401152a6b9e175c1261"),
      },
    ],
    antidote_potions: [],
    healing_potions: [],
    enhancer_potions: [],
    ingredients: [],
  },
  name: "JUAN BENITO AYESTARAN",
  nickname: "Solario",
  email: "juan.benito@ikasle.aeg.eus",
  avatar:
    "https://lh3.googleusercontent.com/a-/ALV-UjXCKq64hoHCty8uiyr8PPQ_6c-dnc6w4iwftZu1NqzavBokUuc=s240-p-k-rw-no",
  classroom_Id: "106812413520557607922",
  level: 45,
  experience: 77053,
  is_active: true,
  profile: {
    name: "Pariah",
    description:
      "Expelled from society and condemned to wander alone, the Pariah is a figure marked by suffering and resilience...",
    image: "/images/profiles/pariah.jpg",
    attributes: [
      {
        name: "Intelligence",
        description:
          "The intelligence controls the chance of success when using a potion",
        value: 0,
        _id: new Types.ObjectId("69501d00f16eff46c25c39b2"),
      },
      {
        name: "Dexterity",
        description:
          "Manages the chance of success when using a melee weapon and the damage a missile weapon does",
        value: 5,
        _id: new Types.ObjectId("69501d00f16eff46c25c39b3"),
      },
      {
        name: "Insanity",
        description: "Indicates the state of mental health...",
        value: 24,
        _id: new Types.ObjectId("69501d00f16eff46c25c39b4"),
      },
      {
        name: "Charisma",
        description: "Indicates the chance to attack first in the next round",
        value: 0,
        _id: new Types.ObjectId("69501d00f16eff46c25c39b5"),
      },
      {
        name: "Constitution",
        description:
          "Indicates the number of Hit Points an adventurer starts with",
        value: 0,
        _id: new Types.ObjectId("69501d00f16eff46c25c39b6"),
      },
      {
        name: "Strength",
        description:
          "Manages the chance of success when using a melee weapon...",
        value: 1,
        _id: new Types.ObjectId("69501d00f16eff46c25c39b7"),
      },
    ],
    _id: new Types.ObjectId("6687c31b7a5ce485a0eed477"),
  },
  tasks: [
    { _id: new Types.ObjectId("692839f7b1b502cce59e2db7") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2db8") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2db9") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dba") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dbb") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dbc") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dbd") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dbe") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dbf") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dc0") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dc1") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dc2") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dc3") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dc4") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dc5") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dc6") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dc7") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dc8") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dc9") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dca") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dcb") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dcc") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dcd") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dce") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dcf") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dd0") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dd1") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dd2") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dd3") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dd4") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dd5") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dd6") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dd7") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dd8") },
    { _id: new Types.ObjectId("692839f7b1b502cce59e2dd9") },
    {
      classroomId: "106812413520557607922",
      courseWorkName: "IOT-1",
      grade: 10,
      selectedAssignment: "828283312948",
      maxPoints: 10,
      _id: new Types.ObjectId("692839f7b1b502cce59e2f33"),
    },
    {
      classroomId: "106812413520557607922",
      courseWorkName: "IOT-2",
      grade: 10,
      selectedAssignment: "828290048810",
      maxPoints: 10,
      _id: new Types.ObjectId("6932adfcaf14cb40b5890bb9"),
    },
    {
      classroomId: "106812413520557607922",
      courseWorkName: "IOT-2",
      grade: 10,
      selectedAssignment: "828290048810",
      maxPoints: 10,
      _id: new Types.ObjectId("6932ae3faf14cb40b5891707"),
    },
    {
      classroomId: "106812413520557607922",
      courseWorkName: "IOT-3",
      grade: 10,
      selectedAssignment: "792280352950",
      maxPoints: 10,
      _id: new Types.ObjectId("6932ae75af14cb40b589273a"),
    },
    {
      classroomId: "106812413520557607922",
      courseWorkName: "ALTAR-IV",
      grade: 33,
      selectedAssignment: "800982402618",
      maxPoints: 40,
      _id: new Types.ObjectId("6932aeecaf14cb40b5893e7f"),
    },
    {
      classroomId: "106812413520557607922",
      courseWorkName: "MORTIMER'S REVELATIONS I ",
      grade: 15,
      selectedAssignment: "800982402636",
      maxPoints: 25,
      _id: new Types.ObjectId("6932c147af14cb40b58997c1"),
    },
  ],
  gold: 19736,
  created_date: "2024-09-17T10:56:54.478Z",
  isBetrayer: false,
  skills: [
    {
      skill: new Types.ObjectId("684804a6022ac850c49be874"),
      activeLevels: [],
      _id: new Types.ObjectId("68f60abe23ba11558fd80447"),
    },
    {
      skill: new Types.ObjectId("684804a6022ac850c49be875"),
      activeLevels: [0, 1, 2],
      _id: new Types.ObjectId("68f60abe23ba11558fd80448"),
    },
    {
      skill: new Types.ObjectId("684804a6022ac850c49be876"),
      activeLevels: [],
      _id: new Types.ObjectId("68f60abe23ba11558fd80449"),
    },
    {
      skill: new Types.ObjectId("684804a6022ac850c49be877"),
      activeLevels: [],
      _id: new Types.ObjectId("68f60abe23ba11558fd8044a"),
    },
    {
      skill: new Types.ObjectId("684804a6022ac850c49be878"),
      activeLevels: [],
      _id: new Types.ObjectId("68f60abe23ba11558fd8044b"),
    },
    {
      skill: new Types.ObjectId("684804a6022ac850c49be879"),
      activeLevels: [],
      _id: new Types.ObjectId("68f60abe23ba11558fd8044c"),
    },
    {
      skill: new Types.ObjectId("684804a6022ac850c49be87a"),
      activeLevels: [],
      _id: new Types.ObjectId("68f60abe23ba11558fd8044d"),
    },
    {
      skill: new Types.ObjectId("684804a6022ac850c49be87b"),
      activeLevels: [],
      _id: new Types.ObjectId("68f60abe23ba11558fd8044e"),
    },
    {
      skill: new Types.ObjectId("68626fd7f87edf17ce379b45"),
      activeLevels: [],
      _id: new Types.ObjectId("68f60abe23ba11558fd8044f"),
    },
    {
      skill: new Types.ObjectId("68626fd7f87edf17ce379b46"),
      activeLevels: [0, 1, 2],
      _id: new Types.ObjectId("68f60abe23ba11558fd80450"),
    },
  ],
  isInside: false,
  is_in_tower_entrance: false,
  is_inside_tower: false,
  card_id: "492f8756",
  has_been_summoned_to_hos: true,
  found_artifacts: [],
  has_completed_artifacts_search: true,
  is_inside_hs: false,
  __v: 8,
  diseases: [],
  isCursed: false,
};

export { MOCKED_PLAYER };
